<a href="https://colab.research.google.com/github/mayank261193/Rebounce-Applied-AI-and-Analytics-Codes/blob/main/Retail_Online_Mayank.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Retail Store data analysis**

### **Import Libraries**

In [75]:
import pandas as pd
import numpy as np

### **Load Dataset**

In [76]:
#Using url to read file
url = "https://huggingface.co/datasets/aarav912/online-retail/resolve/main/online_retail.csv"
df = pd.read_csv(url)

### **Understand  the Data**

In [77]:
#First five Rows

df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [78]:
#Shape of Data
print(f"(rows,coloumns):{df.shape}")

(rows,coloumns):(541909, 8)

In [79]:
#Coloumns Names
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

In [80]:
#Data type of coloumn heads
df.dtypes

InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

In [81]:
# Count of  missing values in each coloumn
df.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [82]:
# Number of duplicate rows
df.duplicated().sum()

np.int64(5268)

### **Do columns Need cleaning?**
No columns needs cleaning as empty cells could filled with every data update.

### **Clean the data**

In [83]:
df.dropna(subset=['CustomerID'], inplace=True)

print(f"Missing CustomerID values after drop:{df['CustomerID'].isna().sum()}")
print(f"Shape after dropping:{df.shape}")
# I opted to drop the missing values because without cutomer ID data is useless.

Missing CustomerID values after drop:0
Shape after dropping:(406829, 8)

In [84]:
#Convert InvoiceDate type into datetime
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
df.dtypes

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID            float64
Country                object
dtype: object

In [85]:
#Dropping duplicate rows
df = df.drop_duplicates()
df.shape

(401604, 8)

In [86]:
#Remove rows where Quantity is zero or negative, or where UnitPrice is zero or negative
df = df[(df["Quantity"] > 0) & (df["UnitPrice"] > 0)]
df.shape

(392692, 8)

### **Create Sales column**

In [87]:
# Create a new column: Sales = Quantity × UnitPrice.
df["Sales"] = df["Quantity"] * df["UnitPrice"]
df.shape

(392692, 9)

### **Numpy Analysis**

In [88]:
#Find statistical parameters usign inbuilt functions
import numpy as np

sales = df["Sales"].to_numpy()

print("Mean:", np.mean(sales))
print("Median:", np.median(sales))
print("Minimum:", np.min(sales))
print("Maximum:", np.max(sales))
print("Standard Deviation:", np.std(sales))
#The data is right skewed as mean>median which means majority of sales below median.

Mean: 22.6314997351614
Median: 12.45
Minimum: 0.001
Maximum: 168469.6
Standard Deviation: 311.0988282235734

### **Pandas filtering**

In [89]:
#Sales above 500
count = (df["Sales"] > 500).sum()
print("Transactions above 500:", count)

Transactions above 500: 913

In [90]:
#10 largest sales
top_10 = df.sort_values("Sales", ascending=False).head(10)
print(top_10)

       InvoiceNo StockCode                          Description  Quantity  \
540421    581483     23843          PAPER CRAFT , LITTLE BIRDIE     80995
61619     541431     23166       MEDIUM CERAMIC TOP STORAGE JAR     74215
222680    556444     22502       PICNIC BASKET WICKER 60 PIECES        60
173382    551697      POST                              POSTAGE         1
348325    567423     23243  SET OF TEA COFFEE SUGAR TINS PANTRY      1412
160546    550461     21108   FAIRY CAKE FLANNEL ASSORTED COLOUR      3114
52711     540815     21108   FAIRY CAKE FLANNEL ASSORTED COLOUR      3114
421601    573003     23084                   RABBIT NIGHT LIGHT      2400
52709     540815    85123A   WHITE HANGING HEART T-LIGHT HOLDER      1930
160542    550461    85123A   WHITE HANGING HEART T-LIGHT HOLDER      1930

               InvoiceDate  UnitPrice  CustomerID         Country      Sales
540421 2011-12-09 09:15:00       2.08     16446.0  United Kingdom  168469.60
61619  2011-01-18 10:01:00       1.04     12346.0  United Kingdom   77183.60
222680 2011-06-10 15:28:00     649.50     15098.0  United Kingdom   38970.00
173382 2011-05-03 13:46:00    8142.75     16029.0  United Kingdom    8142.75
348325 2011-09-20 11:05:00       5.06     17450.0  United Kingdom    7144.72
160546 2011-04-18 13:20:00       2.10     15749.0  United Kingdom    6539.40
52711  2011-01-11 12:55:00       2.10     15749.0  United Kingdom    6539.40
421601 2011-10-27 12:11:00       2.08     14646.0     Netherlands    4992.00
52709  2011-01-11 12:55:00       2.55     15749.0  United Kingdom    4921.50
160542 2011-04-18 13:20:00       2.40     15749.0  United Kingdom    4632.00

In [91]:
#transactions come from Germany
germany = df[df["Country"] == "Germany"]
print(germany)

       InvoiceNo StockCode                          Description  Quantity  \
1109      536527     22809              SET OF 6 T-LIGHTS SANTA         6
1110      536527     84347  ROTATING SILVER ANGELS T-LIGHT HLDR         6
1111      536527     84945   MULTI COLOUR SILVER T-LIGHT HOLDER        12
1112      536527     22242        5 HOOK HANGER MAGIC TOADSTOOL        12
1113      536527     22244           3 HOOK HANGER MAGIC GARDEN        12
...          ...       ...                                  ...       ...
541801    581578     22993         SET OF 4 PANTRY JELLY MOULDS        12
541802    581578     22907     PACK OF 20 NAPKINS PANTRY DESIGN        12
541803    581578     22908        PACK OF 20 NAPKINS RED APPLES        12
541804    581578     23215     JINGLE BELL HEART ANTIQUE SILVER        12
541805    581578     22736          RIBBON REEL MAKING SNOWMEN         10

               InvoiceDate  UnitPrice  CustomerID  Country  Sales
1109   2010-12-01 13:04:00       2.95     12662.0  Germany  17.70
1110   2010-12-01 13:04:00       2.55     12662.0  Germany  15.30
1111   2010-12-01 13:04:00       0.85     12662.0  Germany  10.20
1112   2010-12-01 13:04:00       1.65     12662.0  Germany  19.80
1113   2010-12-01 13:04:00       1.95     12662.0  Germany  23.40
...                    ...        ...         ...      ...    ...
541801 2011-12-09 12:16:00       1.25     12713.0  Germany  15.00
541802 2011-12-09 12:16:00       0.85     12713.0  Germany  10.20
541803 2011-12-09 12:16:00       0.85     12713.0  Germany  10.20
541804 2011-12-09 12:16:00       2.08     12713.0  Germany  24.96
541805 2011-12-09 12:16:00       1.65     12713.0  Germany  16.50

[9025 rows x 9 columns]

In [92]:
#transactions have a Quantity above 1,000
transactions = df[df["Quantity"] > 1000]
print(transactions)
#They are wholesale orders hence data seems believable

       InvoiceNo StockCode                        Description  Quantity  \
4850      536809     84950     ASSORTED COLOUR T-LIGHT HOLDER      1824
4945      536830     84077  WORLD WAR 2 GLIDERS ASSTD DESIGNS      2880
4946      536830     21915             RED  HARMONICA IN BOX       1400
6365      536890    17084R              ASSORTED INCENSE PACK      1440
16435     537659     22189            CREAM HEART CARD HOLDER      1008
...          ...       ...                                ...       ...
533812    581115     22413    METAL SIGN TAKE IT OR LEAVE IT       1404
534952    581175     23084                 RABBIT NIGHT LIGHT      1440
540070    581458     22197                     POPCORN HOLDER      1500
540071    581459     22197                     POPCORN HOLDER      1200
540421    581483     23843        PAPER CRAFT , LITTLE BIRDIE     80995

               InvoiceDate  UnitPrice  CustomerID         Country      Sales
4850   2010-12-02 16:48:00       0.55     15299.0  United Kingdom    1003.20
4945   2010-12-02 17:38:00       0.18     16754.0  United Kingdom     518.40
4946   2010-12-02 17:38:00       1.06     16754.0  United Kingdom    1484.00
6365   2010-12-03 11:48:00       0.16     14156.0            EIRE     230.40
16435  2010-12-07 16:43:00       2.31     18102.0  United Kingdom    2328.48
...                    ...        ...         ...             ...        ...
533812 2011-12-07 12:20:00       2.75     15195.0  United Kingdom    3861.00
534952 2011-12-07 15:16:00       1.79     14646.0     Netherlands    2577.60
540070 2011-12-08 18:45:00       0.72     17949.0  United Kingdom    1080.00
540071 2011-12-08 18:46:00       0.72     17949.0  United Kingdom     864.00
540421 2011-12-09 09:15:00       2.08     16446.0  United Kingdom  168469.60

[104 rows x 9 columns]

### **GroupBy and aggregation**

In [93]:
#Data summary
summary = df.groupby("Country").agg(
    Number_of_Transactions=("Country", "count"),
    Total_Sales=("Sales", "sum"),
    Average_Sales=("Sales", "mean")
).reset_index().sort_values("Total_Sales", ascending=False)

print(f"{summary}\n The country with the biggest total is rarely the one with\n the biggest average because the number of transactions are varying directly \nwith sales hence average country with biggest total sale is minimum")

                 Country  Number_of_Transactions  Total_Sales  Average_Sales
35        United Kingdom                  349203  7285024.644      20.861862
23           Netherlands                    2359   285446.340     121.003111
10                  EIRE                    7226   265262.460      36.709446
14               Germany                    9025   228678.400      25.338327
13                France                    8326   208934.310      25.094200
0              Australia                    1181   138453.810     117.234386
30                 Spain                    2479    61558.560      24.832013
32           Switzerland                    1841    56443.950      30.659397
3                Belgium                    2031    41196.340      20.283772
31                Sweden                     450    38367.830      85.261844
19                 Japan                     321    37416.370     116.561900
24                Norway                    1071    36165.440      33.767918
26              Portugal                    1453    33375.840      22.970296
12               Finland                     685    22546.080      32.913985
29             Singapore                     222    21279.290      95.852658
6        Channel Islands                     747    20440.540      27.363507
9                Denmark                     380    18955.340      49.882474
18                 Italy                     758    17483.240      23.064960
7                 Cyprus                     603    13502.850      22.392786
1                Austria                     398    10198.680      25.624824
25                Poland                     330     7334.650      22.226212
17                Israel                     245     7215.840      29.452408
15                Greece                     145     4760.520      32.831172
16               Iceland                     182     4310.000      23.681319
5                 Canada                     151     3666.380      24.280662
33                   USA                     179     3580.390      20.002179
22                 Malta                     112     2725.590      24.335625
36           Unspecified                     241     2660.770      11.040539
34  United Arab Emirates                      68     1902.280      27.974706
20               Lebanon                      45     1693.880      37.641778
21             Lithuania                      35     1661.060      47.458857
11    European Community                      60     1300.250      21.670833
4                 Brazil                      32     1143.600      35.737500
27                   RSA                      57     1002.310      17.584386
8         Czech Republic                      25      826.740      33.069600
2                Bahrain                      17      548.400      32.258824
28          Saudi Arabia                       9      145.920      16.213333
 The country with the biggest total is rarely the one with
 the biggest average because the number of transactions are varying directly
with sales hence average country with biggest total sale is minimum

### **Merge/region analysis**

In [94]:
#create dataframe from dictionary
region_lookup = {    "United Kingdom": "Europe",
                 "France": "Europe",    "Germany": "Europe",
                     "Spain": "Europe",    "Netherlands": "Europe",
                     "Belgium": "Europe",    "Switzerland": "Europe",
                     "Portugal": "Europe",    "Australia": "Oceania",
                     "Japan": "Asia",    "USA": "Americas",
                }
region_df = pd.DataFrame(list(
    region_lookup.items()),
    columns=["Country", "Region"]
)

print(region_df)

           Country    Region
0   United Kingdom    Europe
1           France    Europe
2          Germany    Europe
3            Spain    Europe
4      Netherlands    Europe
5          Belgium    Europe
6      Switzerland    Europe
7         Portugal    Europe
8        Australia   Oceania
9            Japan      Asia
10             USA  Americas

In [95]:
#Left merge
summary = pd.merge(
    summary,
    region_df,
    on="Country",
    how="left"
)

summary["region_df"] = summary["Region"].fillna("Other")

print(summary)

                 Country  Number_of_Transactions  Total_Sales  Average_Sales  \
0         United Kingdom                  349203  7285024.644      20.861862
1            Netherlands                    2359   285446.340     121.003111
2                   EIRE                    7226   265262.460      36.709446
3                Germany                    9025   228678.400      25.338327
4                 France                    8326   208934.310      25.094200
5              Australia                    1181   138453.810     117.234386
6                  Spain                    2479    61558.560      24.832013
7            Switzerland                    1841    56443.950      30.659397
8                Belgium                    2031    41196.340      20.283772
9                 Sweden                     450    38367.830      85.261844
10                 Japan                     321    37416.370     116.561900
11                Norway                    1071    36165.440      33.767918
12              Portugal                    1453    33375.840      22.970296
13               Finland                     685    22546.080      32.913985
14             Singapore                     222    21279.290      95.852658
15       Channel Islands                     747    20440.540      27.363507
16               Denmark                     380    18955.340      49.882474
17                 Italy                     758    17483.240      23.064960
18                Cyprus                     603    13502.850      22.392786
19               Austria                     398    10198.680      25.624824
20                Poland                     330     7334.650      22.226212
21                Israel                     245     7215.840      29.452408
22                Greece                     145     4760.520      32.831172
23               Iceland                     182     4310.000      23.681319
24                Canada                     151     3666.380      24.280662
25                   USA                     179     3580.390      20.002179
26                 Malta                     112     2725.590      24.335625
27           Unspecified                     241     2660.770      11.040539
28  United Arab Emirates                      68     1902.280      27.974706
29               Lebanon                      45     1693.880      37.641778
30             Lithuania                      35     1661.060      47.458857
31    European Community                      60     1300.250      21.670833
32                Brazil                      32     1143.600      35.737500
33                   RSA                      57     1002.310      17.584386
34        Czech Republic                      25      826.740      33.069600
35               Bahrain                      17      548.400      32.258824
36          Saudi Arabia                       9      145.920      16.213333

      Region region_df
0     Europe    Europe
1     Europe    Europe
2        NaN     Other
3     Europe    Europe
4     Europe    Europe
5    Oceania   Oceania
6     Europe    Europe
7     Europe    Europe
8     Europe    Europe
9        NaN     Other
10      Asia      Asia
11       NaN     Other
12    Europe    Europe
13       NaN     Other
14       NaN     Other
15       NaN     Other
16       NaN     Other
17       NaN     Other
18       NaN     Other
19       NaN     Other
20       NaN     Other
21       NaN     Other
22       NaN     Other
23       NaN     Other
24       NaN     Other
25  Americas  Americas
26       NaN     Other
27       NaN     Other
28       NaN     Other
29       NaN     Other
30       NaN     Other
31       NaN     Other
32       NaN     Other
33       NaN     Other
34       NaN     Other
35       NaN     Other
36       NaN     Other

In [96]:
#Group by region
region_sales = (
    summary.groupby("Region")["Total_Sales"]
    .sum()
    .reset_index()
    .sort_values("Total_Sales", ascending=False)
)

print(region_sales)

     Region  Total_Sales
2    Europe  8200658.384
3   Oceania   138453.810
1      Asia    37416.370
0  Americas     3580.390

### **Answer the questions**

1. Which country generated the highest total sales?

```
United kingdom
```
2. Which country had the highest average transaction value?

```
United Kingdom
```
3. Which region performed best?

```
Europe
```

4. What is one interesting pattern you noticed in the data?
```
Number of transaction following similar trend as total sales
```
5. What is one data-quality problem you ran into, and how did you handle it?
```
Removing duplicate rows and for that i used drop duplicates method.
```

### **Final Finding**



### 1. Important finding
```
**The country with the highest total sales is not necessarily
the country with the highest average sales.**Total sales depend
heavily on the number of transactions, while average sales shows
the typical value of an individual transaction.
```

### 2. One comparison
```
If the mean is noticeably higher than the median, it suggests that
some high-value transactions are pulling the average upward
```

### 3. Observation about the data
```
**Sales are likely right-skewed**
This would explain why the mean is higher than the median and
indicates that the typical transaction is better represented
by the median.
```
### 4. Limitation
```
**The data required cleaning before analysis.** Duplicate rows were
removed, and transactions with `Quantity <= 0` or `UnitPrice <= 0`
were excluded because they represented cancellations or adjustments
rather than genuine sales. Therefore, the calculated sales statistics
describe the **cleaned sales transactions**, not the original raw
dataset.
```